import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/styles/main.scss'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import '@/styles/layout.scss'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column min-vh-100 bg-light`}
      >
        <NavBar />
        <main className='mainLayout container flex-grow-1'>{children}</main>

        <Footer />
      </body>
    </html>
  )
}
